version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vite
    versions:
    - 2.1.2
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.35
