<template lang="pug">
section-title(text="Política de privacidad y protección de datos")
.text-justify.py-4
  | Las partes se comprometen expresamente a cumplir con las obligaciones establecidas en el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos (“RGPD”) así como de conformidad con la normativa nacional de desarrollo de dicho Reglamento. En particular, con lo establecido en la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y garantía de los derechos digitales (“LOPDGDD”).
.text-justify.py-4
  | Los datos de carácter personal que cada parte entregue a la otra serán única y exclusivamente aquéllos estrictamente necesarios para el mantenimiento de la relación contractual y solamente podrán ser utilizados por la otra parte para el cumplimiento de los fines de este contrato y durante su periodo de vigencia. Una vez terminada la relación contractual, los datos solo podrán ser conservados y utilizados para dar cumplimiento a obligaciones legales y por los plazos de prescripción de éstas. Queda expresamente prohibida a ambas partes la cesión a terceros de los datos personales obtenidos de conformidad con lo previsto en el presente apartado salvo para aquellos casos en que la transferencia sea necesaria para la ejecución de este contrato o para dar cumplimiento a una obligación legal. Las personas a las que se refieran estos datos pueden ejercitar sus derechos de acceso, rectificación, supresión, limitación del tratamiento, portabilidad y oposición a decisiones individuales automatizadas ante la parte contraria (mediante escrito dirigido al domicilio social C/ Francisco de Rojas 6, Madrid, 28010), y podrán presentar una reclamación ante la Agencia Española de Protección de Datos por cualquier vulneración de la normativa de protección de datos que le sea imputable a la parte responsable del tratamiento correspondiente.
.text-justify.py-4
  | La Asociación es responsable del tratamiento de los datos de carácter personal del donante necesarios para la prestación de esta inscripción y apadrinamiento. Asimismo, el donante otorga su autorización expresa a la Asociación para que ésta pueda enviarle comunicaciones a su email (indicado en el presente contrato) o en cualquier otro soporte, relacionadas y/o necesarias con su inscripción y apadrinamiento a la Asociación.
</template>
